/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const CANCEL_EDIT_EMPLOYEE = 'CANCEL_EDIT_EMPLOYEE';

export const SET_CAN_EDIT_EMPLOYEE = 'SET_CAN_EDIT_EMPLOYEE';

export const SET_EMPLOYEES = 'SET_EMPLOYEES';

export const SET_RECRUIT = 'SET_RECRUIT';
export const FIND_RECRUIT = 'FIND_RECRUIT';
export const SET_RECRUITS_SEARCH_RESULT = 'SET_RECRUITS_SEARCH_RESULT';

export const SET_COMMENTS = 'SET_COMMENTS';

export const SET_NEWS = 'SET_NEWS';
export const ADD_NEWS = "ADD_NEWS";
export const CREATE_NEWS = 'CREATE_NEWS';
export const CANCEL_CREATE_NEWS = 'CANCEL_CREATE_NEWS';

export const INITIATE_SERVICES_WITH_TOKEN = "INITIATE_SERVICES_WITH_TOKEN";
export const GET_SERVICES = "GET_SERVICES";
